global:
  resolve_timeout: 1m
# The directory from which notification templates are read.
templates:
  - '/etc/alertmanager/template/*.tmpl'
receivers:
    - name: 'slack-notificaions'
      email_configs:
        - to: ##test@gmail.com
          from: #mail
          smarthost: #smtp.gmail.com:587
          auth_username: #test@gmail.com
          auth_identity: #test@gmail.com
          auth_password: #vbwnlvcayadmcjsi
          send_resolved: true
route:
      group_interval: 5m
      group_wait: 10s
      receiver: 'slack-notificaions'
      repeat_interval: 3h