apiVersion: v1
kind: Pod
metadata:
  name: prometheusxgrafana
spec:
  containers:
  - name: prometheus
    image: quay.io/prometheus/prometheus
    ports:
    - containerPort: 9090
      hostPort: 9090
      name: prometheus
    volumeMounts:
    - name: prom-data
      mountPath: /etc/prometheus
  - name: grafana
    image: docker.io/grafana/grafana-enterprise
    ports:
    - containerPort: 3000
      hostPort: 3000
      name: grafana
    volumeMounts:
    - name: grafana-data
      mountPath: /var/lib/grafana
  - name: blackbox-exporter
    image: quay.io/prometheus/blackbox-exporter
    args:
      - "--config.file:/config/blackbox.yaml"
    ports:
      - containerPort: 9115
        hostPort: 9115
        name: blackbox-exporter
    volumeMounts:
      - mountPath: /config
        name: config
        readOnly: true
  volumes:
  - name: prom-data
    persistentVolumeClaim:
      claimName: prom-data
  - name: grafana-data
    persistentVolumeClaim:
      claimName: grafana-data
  - name: config
    configMap:
      name: blackbox-exporter-config
